# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - "*"
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    strategy:
      matrix:
        node-version: [18.15.0]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test
    - run: npm run build
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@8e58d20d0f6c8773181f43eb74d6a05e3099571d
      with:
        branches: |
          [
            'main',
            {
              name: 'beta',
              prerelease: true
            }
          ]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
