# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - "*"
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
      # See https://docs.npmjs.com/trusted-publishers
      # Find the latest version with `npm info npm@latest version`
    - name: Install suitable NPM version for trusted publishing
      run: npm install -g npm@11.12.0
    - run: npm ci
    - run: npm run test
    - run: npm run build
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@36bdefbcf6d8854593f95b76e7d567f89d76181e
      with:
        branches: |
          [
            'main',
            {
              name: 'beta',
              prerelease: true
            }
          ]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
